# Strings are sequences

A string is a sequence of characters. You can access the characters one at a time with the bracket operator:

In [1]:
animal = 'ferret'
letter = animal[1]

The second statement selects character number 1 from fruit and assigns it to letter.

The expression in brackets is called an index. The index indicates which character in the sequence you want (hence the name).

But you might not get what you expect:

In [2]:
letter

'e'

For most people, the first letter of 'ferret' is f, not e. But for computer scientists, the index is an offset from the beginning of the string, and the offset of the first letter is zero.

In [3]:
letter = animal[0]
letter

'f'

So f is the 0th letter (“zero-eth”) of 'ferret', 'e' is the 1th letter (“one-eth”), and 'r' is the 2th letter (“two-eth”).

As an index you can use an expression that contains variables and operators:

In [5]:
i = 1
animal[i]

'e'

In [6]:
animal[i+1]

'r'

But the value of the index has to be an integer. Otherwise you get:

In [7]:
letter = animal[1.5]

TypeError: string indices must be integers

## `len`

`len` is a built-in function that returns the number of characters in a string:

In [8]:
animal = 'ferret'
len(animal)

6

To get the last letter of a string, you might be tempted to try something like this:

In [9]:
length = len(animal)
last = animal[length]

IndexError: string index out of range

The reason for the `IndexError` is that there is no letter in ’ferret’ with the index 6. Since we started counting at zero, the six letters are numbered 0 to 5. To get the last character, you have to subtract 1 from length:

Or you can use negative indices, which count backward from the end of the string. The expression `animal[-1]` yields the last letter, `animal[-2]` yields the second to last, and so on. 

In [10]:
last = animal[length-1]
last

't'

# Lists

Like a string, a `list` is a sequence of values. In a string, the values are characters; in a list, they can be any type. The values in a list are called elements or sometimes items.

There are several ways to create a new list; the simplest is to enclose the elements in square brackets (`[` and `]`):

In [2]:
list1 = [10, 20, 30, 40]
list2 = ['ferret', 2.0, 5, [10, 30]]

The first example is a list of four integers. The second demonstrates that the elements of a list don’t have to be the same type. In `list2` we have a string, a float, an integer, and another list.
A list within another list is nested.

A list that contains no elements is called an empty list; you can create one with empty brackets, `[]`.

## Lists are mutable

The syntax for accessing the elements of a list is the same as for accessing the characters of a string — the bracket operator. The expression inside the brackets specifies the index. Remember that the indices start at 0:

In [3]:
list2[0]

'ferret'

If we want to modify an element of a list we can use the bracket operator on the left hand side of an assignment:

In [4]:
print(list2)
list2[1] = 'rat'
print(list2)

['ferret', 2.0, 5, [10, 30]]
['ferret', 'rat', 5, [10, 30]]


**WARNING**: Strings are not mutable!

While both strings and lists are sequences we are not allowed to change characters of strings. The following code raises an error.

In [23]:
animal = 'ferret'
animal[0] = 'b'

TypeError: 'str' object does not support item assignment

## Traversing

A lot of computations involve processing sequences one element at a time. Often they start at the beginning, select each element in turn, do something to it, and continue until the end. This pattern of processing is called a traversal. One way to write a traversal is with a while loop but a more common is with a for loop:

In [5]:
for elem in list2:
    print(elem)

ferret
2.0
5
[10, 30]


Each time through the loop, the next element in the list is assigned to the variable `elem`. The loop continues until no elements are left. Of course you can do the same with a string and print all the characters one after the other.

In [4]:
word = 'Neuron'
for char in word:
    print(char)

N
e
u
r
o
n


This works well if you only need to read the elements of the list. But if you want to write or update the elements, you need the indices. A common way to do that is to combine the built-in functions `range` and `len`:

In [6]:
numbers = [0, 1, 2, 3, 4, 5]
for i in range(len(numbers)):
    numbers[i] = numbers[i] * 2
    
print(numbers)

[0, 2, 4, 6, 8, 10]


This loop traverses the list and updates each element. len returns the number of elements in the list. range returns a list of indices from 0 to n−1, where n is the length of the list. Each time through the loop i gets the index of the next element. The assignment statement in the body uses i to read the old value of the element and to assign the new value.

A for loop over an empty list never runs the body:

In [5]:
empty_list = []
for elem in empty_list:
    print(elem)

## List operations

These operators work in a similar way on strings and lists.

The `+` operator concatenates lists:

In [7]:
a = [1, 2, 3]
b = [4, 5, 6]
c = a + b
c

[1, 2, 3, 4, 5, 6]

The `*` operator repeats a list a given number of times:

In [8]:
print([0] * 4)
print([1, 2, 3] * 3)

[0, 0, 0, 0]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


## List slices

A segment of a list is called a slice. The operator `[n:m]` returns the part of the string from the “n-eth” character to the “m-eth” character, including the first but **excluding the last**. 

In [9]:
t = ['a', 'b', 'c', 'd', 'e', 'f']
print(t[1:3])
print(t[:4])
print(t[3:])

['b', 'c']
['a', 'b', 'c', 'd']
['d', 'e', 'f']


If you omit the first index, the slice starts at the beginning. If you omit the second, the slice goes to the end. So if you omit both, the slice is a copy of the whole list.

In [10]:
t[:]

['a', 'b', 'c', 'd', 'e', 'f']

A slice operator on the left side of an assignment can update multiple elements:

In [11]:
t[1:3] = ['x', 'y']
t

['a', 'x', 'y', 'd', 'e', 'f']

##  List methods

Python provides methods that operate on lists. For example, `append` and `extend` add one or multiple new elements to the end of a list, respectively:

In [13]:
t = ['a', 'b', 'c']
t.append('d')
print(t)
t.extend(['e', 'f'])
print(t)

['a', 'b', 'c', 'd']
['a', 'b', 'c', 'd', 'e', 'f']


`sort` arranges the elements of the list from low to high:

In [6]:
t = ['d', 'c', 'e', 'b', 'a']
t.sort()
t

['a', 'b', 'c', 'd', 'e']

Most list methods are void; they modify the list and return `None`. If you accidentally write `t = t.sort()`, you will be disappointed with the result. 

##  Deleting elements

There are several ways to delete elements from a list. If you know the index of the element you want, you can use pop:

In [15]:
t = ['a', 'b', 'c']
x = t.pop(1)
print(t)
print(x)

['a', 'c']
b


pop modifies the list and returns the element that was removed. If you don’t provide an index, it deletes and returns the last element.

If you don’t need the removed value, you can use the del operator:

In [16]:
t = ['a', 'b', 'c']
del t[1]
t

['a', 'c']

If you know the element you want to remove (but not the index), you can use remove:

In [17]:
t = ['a', 'b', 'c']
t.remove('b')
t

['a', 'c']

The return value from remove is None.

To remove more than one element, you can use del with a slice index:

In [18]:
t = ['a', 'b', 'c', 'd', 'e', 'f']
del t[1:5]
t

['a', 'f']

# Numpy arrays

Numpy arrays ara sequences very similar to lists but more convenient and efficient for scientific computing.

The easiest way to create an array of values is to build it around a list:

In [1]:
import numpy as np
a = np.array([0, 1, 2, 3, 4])
print(a)
print(type(a))
print(a.dtype)

[0 1 2 3 4]
<class 'numpy.ndarray'>
int64


An array looks like a list but it has its own type. Array also have a property `dtype` which tells you the type of their elements.
Reading, writing and slicing work on arrays as they do on lists.

As you can see when you create an array its dtype is inherited by that of the list elements but you can override this behaviour:

In [8]:
a = np.array([0, 1, 2, 3, 4],dtype=float)
print(a)
print(type(a))
print(a.dtype)

[0. 1. 2. 3. 4.]
<class 'numpy.ndarray'>
float64


## `shape`

You can create a multi-dimensional array by passing a nested list to `np.array()` constructor.

You can use `len` on arrays but for multidimensional arrays its advisable to use their property `shape` or the function `np.shape()` which gives the length in each dimension.

In [9]:
b = np.array([[0, 1, 2, 4]]*3)
print(b)
b.shape

[[0 1 2 4]
 [0 1 2 4]
 [0 1 2 4]]


(3, 4)

You can also create arrays initializing them with given values.

In [10]:
z = np.zeros([4, 3])
c = np.ones([5, 2])
d = np.ones([4, 3, 2]) * 3.14
print(z)
print(c)
print(d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[[3.14 3.14]
  [3.14 3.14]
  [3.14 3.14]]

 [[3.14 3.14]
  [3.14 3.14]
  [3.14 3.14]]

 [[3.14 3.14]
  [3.14 3.14]
  [3.14 3.14]]

 [[3.14 3.14]
  [3.14 3.14]
  [3.14 3.14]]]


## Slices

You can slice arrays as you do with lists, except that multidimensional arrays need one index for each dimension.

In [11]:
z[:2, 0] = 1
print(z)
d[:, :, 0]

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

## Math on arrays

Mathematical operator work with arrays but they behave differently than with lists.

In [12]:
z + d[:, :, 0]

array([[4.14, 3.14, 3.14],
       [4.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

Mathematical operators and mathematical functions defined in numpy apply to arrays element-wise.

In [13]:
a = np.ones([2, 3])*np.pi
b = np.ones([2, 3])*7
np.sqrt(b/a)

array([[1.49270533, 1.49270533, 1.49270533],
       [1.49270533, 1.49270533, 1.49270533]])

But this means that the two operands need to have the same shape.

In [14]:
c = np.ones([2, 2])*7
c/a

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

## Operations on arrays

### Concatenation

Since the `+` operator performs element-wise sum you can use the function `np.concatenate` to join two arrays.

In [25]:
a = np.array([0, 1, 2, 3])
b = np.concatenate((a, [4]))
print(a)
print(b)

[0 1 2 3]
[0 1 2 3 4]


You can also concatenate arrays of multiple dimensions but you need to specify in which dimension you want to concatenate them.
They also need to have the same number of dimensions and they can only differ in shape for the dimension you concatenate over. Let's see an example.

In [52]:
print(c)
print("c shape: {}".format(c.shape))
d = np.array([[1, 1]])
print(d)
print("d shape: {}".format(d.shape))
np.concatenate((c, d), axis=0)

[[7. 7.]
 [7. 7.]]
c shape: (2, 2)
[[1 1]]
d shape: (1, 2)


array([[7., 7.],
       [7., 7.],
       [1., 1.]])

Here we specify the `axis`, the dimension, we use to concatenate (actually if you don't do it it will try to contatenate by default over the 0-eth axis). The two arrays have the same number of dimensions and they differ in the first dimension, so the concatenation works well. If we try to change the axis we get en error.

In [48]:
np.concatenate((c, d), axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

This might be disappointing since we see that `d` could actually be rotated and concatenated to the end of `c`.
But numpy is not doing this rotation so the concatenation fails.

The above example works because `d` is a two dimensional array. But it has only a single row, so a more intuitive way of coding it would be with a 1-dimensional array.

In [53]:
d = np.array([1, 1])
np.concatenate((c, d), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

However this fails because the two arrays don't have the same number of dimensions.
We can fix that easily by adding an extra dimension to `d` on the fly using `np.newaxis`. by indexing an existing array with `np.newaxis` you can create, guess what, a new axis (of course this creates a new array and don't modify the original).

In [62]:
print(d)
print(d[np.newaxis, :])

[1 1]
[[1 1]]


In [63]:
np.concatenate((c, d[np.newaxis, :]), axis=0)

array([[7., 7.],
       [7., 7.],
       [1., 1.]])

Here we are indexing `d` with a new axis in the right dimension. Thus, if we actually want to concatenate `d` to the right of `c` instead of at the bottom we can put the new axis on the second dimension instead of the first and concatenate on the columns instead of the rows.

In [64]:
np.concatenate((c, d[:, np.newaxis]), axis=1)

array([[7., 7., 1.],
       [7., 7., 1.]])

### Flatten

You can make a multidimensional array 1-dimensional by flattening it, thus stacking all the rows.

In [80]:
print(z)
z.flatten()

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])

you can also stack all the columns instead using the keyword option `order` (the default value is `'C'`).

In [82]:
print(z)
z.flatten(order='F')

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Sorting

You can sort an array with `np.sort`.

In [87]:
q = np.array([3, 2, 5, 1, 4])
np.sort(q)

array([1, 2, 3, 4, 5])

For multidimensional arrays you need to specify on which axis you want `sort` to operate.

In [110]:
w = np.array([[9, 8, 7], [3, 1, 2]])
print(w)
print(np.sort(w, axis=0))
print(np.sort(w, axis=1))

[[9 8 7]
 [3 1 2]]
[[3 1 2]
 [9 8 7]]
[[7 8 9]
 [1 2 3]]


### Delete

You can delete elements by index from an array.

In [89]:
np.delete(q, 1)

array([3, 5, 1, 4])

If the array is multidimensional you need to specify the axis otherwise the array is first flattened.

In [102]:
print(z)
np.delete(z, 1, axis=0)

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

You can also remove more than one index at a time by passing a sequence of indices.

In [100]:
np.delete(z, [0, 1], axis=0)

array([[0., 0., 0.],
       [0., 0., 0.]])

## Few suggestions

1. Be careful with list methods modifing lists in-place and returning None and those returning something.
2. There are several ways to achive the same results (e.g. adding or deleting elements): pick one and stick to it.
3. Sometimes it's not obvious whether you should use a list or an array; numpy arrays are more useful for manipulating numeric values so when in dubt use arrays for sequences of numbers. 

# Exercises

### Exercise 1  

Write a function called nested_sum that takes a list of lists of integers and adds up the elements from all of the nested lists.

### Exercise 2

Write a function called has_duplicates that takes a list and returns True if there is any element that appears more than once. It should not modify the original list.

### Exercise 3

Using the functions you created in previous sessions write a new function that takes a list of neurons center positions and a list of neurons areas and returns a 2D numpy array with pairwise distances between neurons.
The list of neurons center should be a nested list with x and y positions of each center.

### Exercise 4

You can normalize values of a sequence so that they never excede 1 by dividing each eleme element by the value of maximum element of the sequence. Write a function to accomplish this task. Hint: the function `np.max` will be useful.

Another common normalization is the so called standardization or z-score, which consist in subtracting the mean of the sequence and dividing by the standard deviation. Write a function that returns a standardized sequence. Hint: `np.mean`  and `np.std` will make your life easier.

### Exercise 5

The recording of a single neuron has been stored as a binary sequence where a one correspond to a spike in a given time frame. You are given two chunks of the recordings in variables `spikesA` and `spikesB` together with the sequences of the timestamp of each frame in milliseconds and you have to connect them.
1. What is the average firing rate of the neuron?
2. Calculate the moving average firing rate in a window of 100 ms, shifting the window by 20 ms each step.

Hints: the function `np.sum` calculates the sum of all elements of an array; in order to calculate a moving average first initialize an array to store the results with the appropriate number of elements and then iterate of the result array to update each of its elements in turn; you can define a function to calculate the averate firing rate and reuse it here; each window is just a slice of the original spikes array; calculate the moving average firing rate by hand and check that your implementation is correct

In [14]:
spikesA = np.array([0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0])
timesA = np.array([760,  780,  800,  820,  840,  860,  880,  900,  920,  940, 960, 980, 1000, 1020, 1040, 1060, 1080, 1100, 1120])
spikesB= np.array([0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1])
timesB= np.array([120, 140, 160, 180, 200, 220, 240, 260, 280, 300, 320, 340, 360, 380, 400, 420, 440, 460, 480, 500, 520, 540, 560, 580, 600, 620, 640, 660, 680, 700, 720, 740])